# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 105a27b87969c6313258584701de1b0f41ef89a8e20077c59ffd97a0ddca6c70f0b6c50f4b8d40dbf57474647a03a555f84d6985c5830ad9ef7897511900a097

test:
  secret_key_base: c862d40940ccc4a4e60124802d53c244d9698cbf528e7fde5b54f6537d8dc1f915a5dc625a1990da613893d7a8ced44bc257959aeefc91e999d5233b8f9f1a68

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
